# Generated by Django 5.2.15 on 2026-06-13 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(help_text='Meta Phone Number ID', max_length=100)),
                ('waba_id', models.CharField(help_text='Meta WhatsApp Business Account ID', max_length=100)),
                ('access_token', models.TextField(help_text='Meta Permanent Access Token')),
                ('instance_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('webhook_url', models.URLField(blank=True, help_text='User Webhook to receive incoming messages', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, help_text='Meta message identifier', max_length=255, null=True, unique=True)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, help_text='Raw payload sent or received', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappinstance')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('components', models.JSONField(help_text='Header, Body, Footer, Buttons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='whatsapp.whatsappinstance')),
            ],
            options={
                'unique_together': {('instance', 'name', 'language')},
            },
        ),
    ]
