# Generated by Django 5.2.15 on 2026-06-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Gemini or OpenAI API key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='ai_prompt',
            field=models.TextField(blank=True, help_text='Business information / context for the AI agent', null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='bot_mode',
            field=models.CharField(choices=[('off', 'Disabled'), ('ai', 'AI Auto-Reply'), ('qa', 'Q&A Custom Rules')], default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='instance_type',
            field=models.CharField(choices=[('meta', 'Meta Cloud API'), ('web_qr', 'WhatsApp Web (QR Code)')], default='meta', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Connected WhatsApp phone number', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='qr_code',
            field=models.TextField(blank=True, help_text='Base64 QR Code string for scanning', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, help_text='Message identifier', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='access_token',
            field=models.TextField(blank=True, help_text='Meta Permanent Access Token', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='phone_number_id',
            field=models.CharField(blank=True, help_text='Meta Phone Number ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('qrcode', 'Scan QR Code'), ('connecting', 'Connecting'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='waba_id',
            field=models.CharField(blank=True, help_text='Meta WhatsApp Business Account ID', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FAQRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword or question to match', max_length=255)),
                ('answer', models.TextField(help_text='Response to send when matched')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_rules', to='whatsapp.whatsappinstance')),
            ],
        ),
    ]
