# Generated by Django 5.2.15 on 2026-06-18 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappinstance_ai_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='faqrule',
            name='action_payload',
            field=models.TextField(blank=True, help_text='JSON payload/metadata for lists/buttons/files', null=True),
        ),
        migrations.AddField(
            model_name='faqrule',
            name='action_type',
            field=models.CharField(choices=[('text', 'Send Text'), ('image', 'Send Image'), ('file', 'Send File'), ('buttons', 'Send Buttons'), ('list', 'Send List'), ('handover', 'Handover to Agent')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='faqrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faqrule',
            name='matching_type',
            field=models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains Keyword'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('regex', 'Regular Expression')], default='contains', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='profile_picture',
            field=models.TextField(blank=True, help_text='Base64 or URL of WhatsApp avatar', null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='webhook_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='wh_group_member_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='wh_group_member_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='wh_message_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='wh_message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='wh_qr_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='wh_status_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faqrule',
            name='answer',
            field=models.TextField(help_text='Response to send (or action payload details)'),
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('outcome', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='whatsapp.whatsappinstance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('current_step', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='whatsapp.whatsappinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='whatsapp.agreement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('expiry', 'Subscription Expiry'), ('disconnected', 'Disconnected Session'), ('success', 'Operation Success'), ('update', 'System Update')], default='success', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.supportticket')),
            ],
        ),
    ]
