# Generated by Django 5.2.15 on 2026-06-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_agreement_faqrule_action_payload_faqrule_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='ai_model',
            field=models.CharField(default='gemini-2.5-flash', help_text='AI Model Name', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('claude', 'Anthropic Claude'), ('deepseek', 'DeepSeek'), ('groq', 'Groq')], default='gemini', help_text='AI Provider', max_length=50),
        ),
    ]
