# Generated by Django 5.2.15 on 2026-07-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_whatsappinstance_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='business_id',
            field=models.CharField(blank=True, help_text='Meta Business ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='cloud_api_status',
            field=models.CharField(blank=True, help_text='Meta Cloud API Status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='display_name',
            field=models.CharField(blank=True, help_text='Verified Display Name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='embedded_signup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='quality_rating',
            field=models.CharField(blank=True, help_text='Phone Number Quality Rating', max_length=50, null=True),
        ),
    ]
