# Generated by Django 5.2.15 on 2026-08-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_support_ticket_add_assigned_to_and_sender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='priority',
        ),
    ]
