# Generated by Django 5.2.15 on 2026-07-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='message_limit_per_day',
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='broadcasts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='color_gradient',
            field=models.CharField(default='linear-gradient(135deg, #333333, #000000)', max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='icon',
            field=models.CharField(choices=[('vip', 'VIP'), ('max', 'Max'), ('plus', 'Plus'), ('gold', 'Gold'), ('silver', 'Silver'), ('diamond', 'Diamond'), ('basic', 'Basic')], default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='interactive_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_devices_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_messages_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_numbers_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='message_limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='plan',
            name='number_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='support_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('medium', 'Medium'), ('priority', 'Priority'), ('vip', 'VIP')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='webhooks',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_used', models.IntegerField(default=0)),
                ('messages_limit', models.IntegerField(default=10000)),
                ('devices_used', models.IntegerField(default=0)),
                ('devices_limit', models.IntegerField(default=1)),
                ('numbers_used', models.IntegerField(default=0)),
                ('numbers_limit', models.IntegerField(default=1)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='billing.subscription')),
            ],
        ),
    ]
