# Generated by Django 5.2.15 on 2026-07-29 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_plan_message_limit_per_day_plan_ai_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(default='bank_transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
