# Generated by Django 5.2.15 on 2026-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_payment_method_invoice_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('refunded', 'Refunded'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
