# Generated by Django 5.2.15 on 2026-07-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_account_type_profile_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
