# Generated by Django 5.2.15 on 2026-07-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('pending', 'Pending')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('professional', 'Professional'), ('company', 'Company')], default='ordinary', max_length=20),
        ),
    ]
